# Generated by Django 3.2 on 2021-04-26 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 26, 16, 23, 26, 413688), verbose_name='date published'),
        ),
    ]
