# Generated by Django 3.2 on 2021-05-07 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210508_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 8, 1, 24, 40, 801289), verbose_name='date published'),
        ),
    ]
